### ISSUE TITLE
install bug

### ISSUE THREAD

**Issue by paulirish** [danheberden/yeoman-generator-requirejs#1]
``` shell
$ yo requirejs

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

This comes with requirejs, jquery, and grunt all ready to go
What is the name of your app? (danweather)
Description: (An awesome requirejs app)
   create Gruntfile.js
   create package.json
   create bower.json

fs.js:338
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/paulirish/temp/danweather/node_modules/generator-requirejs/app/templates/.gitignore'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.readFileSync (fs.js:182:15)
    at AppGenerator.copy (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/actions/actions.js:74:15)
    at AppGenerator.git (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/app/index.js:83:8)
    at next (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/base.js:275:18)
    at Base.run (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/base.js:286:7)
    at next (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/util/conflicter.js:52:14)
    at conflicter.resolve (/Users/paulirish/temp/danweather/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/util/co~/temp/danweather
$
```

**Comment by danheberden** [comment]
i wonder why `.gitignore` is showing as not present when it's in the repo? :/

**Comment by danheberden** [comment]
Should be resolved with sha#74552284 - @paulirish can you test?

**Comment by paulirish** [comment]
fixed! nice one.

**Comment by addyosmani** [comment]
Should be good to close. Thanks for the fix!
