### ISSUE TITLE
Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by sgentile** [danheberden/yeoman-generator-requirejs#11]
When I run the yo requirejs I get the following error:

/usr/local/lib/node_modules/generator-requirejs/app/index.js:30
  '\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow.bold + '    |' +
                                                         ^
TypeError: Cannot read property 'bold' of undefined
    at AppGenerator.askFor (/usr/local/lib/node_modules/generator-requirejs/app/index.js:30:58)
    at next (/usr/local/lib/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/base.js:275:18)
    at AppGenerator.run (/usr/local/lib/node_modules/generator-requirejs/node_modules/yeoman-generator/lib/base.js:289:4)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env.js:433:20)
    at init (/usr/local/lib/node_modules/yo/bin/yo:98:7)
    at pre (/usr/local/lib/node_modules/yo/bin/yo:110:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/bin/yo:135:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by danheberden** [comment]
@sgentile can you try re-installing? i just updated the package https://npmjs.org/package/generator-requirejs

**Comment by sgentile** [comment]
Fixed thanks!
